services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - frontend_network  # Only accessible to frontend and API

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - frontend_network  # Connects to frontend
      - backend_network   # Connects to database

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - backend_network  # Only API can access this
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  frontend_network:
  backend_network:

volumes:
  postgres_data:
